### ISSUE TITLE
Crash with MendingXP on tick

### ISSUE THREAD

**Issue by idgarad** [ChaoticTrials/UtilitiX#15]
Using All The Mods 7 and getting a crash consistently. Recently updated to your newest release and noticed the error:

`java.util.ConcurrentModificationException: null
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1855) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at de.melanx.utilitix.content.BetterMending.pullXPClient(BetterMending.java:87) ~[UtilitiX-1.18.1-0.3.9.jar%23289!/:1.18.1-0.3.9] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_792_BetterMending_pullXPClient_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:876) ~[forge-1.18.1-39.0.66-universal.jar%23303!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1733) ~[client-1.18.1-20211210.034407-srg.jar%23299!/:?] `

Something about your changes with the PullXP function seems to be broke, at least as far as the mod pack is concerned. Don't have the time to do an isolated test but something seems off. Tried disabling the config for it but the function still is running I think.

**Comment by idgarad** [comment]
I got a few minutes. I reverted to the 0.38 pack and no crash so there is something borked with the pullXPClient code.

**Comment by MelanX** [comment]
Thanks, I’ll work on it as soon as possible.
